### ISSUE TITLE
牛逼+刁爆天

### ISSUE THREAD

**Issue by intgogo** [Kesoyuh/Gomoku#1]
如题~非常感谢，对我写另外一种游戏的AI算法启发很大！！！

**Comment by genosage** [comment]
客气~

**Comment by intgogo** [comment]
不过~~~我刚刚在appstore里面找了另外一个叫做五子棋大师的游戏，跟它打了两把，咱都输了- -

**Comment by intgogo** [comment]
搜索 五子棋大师 第一个app

**Comment by intgogo** [comment]
我用iphone5玩那个app，速度比我用iphone7玩你这个稍稍慢一点，但是无论先手还是后手，都输给了对方的特级大师

**Comment by genosage** [comment]
是的，cnvs 的五子棋大师目前应该是 iOS 平台棋力最高的 APP 之一了，我们目前的版本的确跟它有较大差距，不过很可惜它是直接抄袭波兰五子棋引擎 Carbon 的作品，有兴趣的话你可以看看：https://github.com/gomoku/Carbon-Gomoku
