### ISSUE TITLE
简单难度AI的那些值是随便定的么？

### ISSUE THREAD

**Issue by OtakuAndFitness** [Kesoyuh/Gomoku#2]
就是这些：
// tuple is empty  
GGTupleTypeBlank = 7,  
// tuple contains a black chess  
GGTupleTypeB = 35,  
// tuple contains two black chesses  
GGTupleTypeBB = 800,  
// tuple contains three black chesses  
GGTupleTypeBBB = 15000,  
// tuple contains four black chesses  
GGTupleTypeBBBB = 800000,  
// tuple contains a white chess  
GGTupleTypeW = 15,  
// tuple contains two white chesses  
GGTupleTypeWW = 400,  
// tuple contains three white chesses  
GGTupleTypeWWW = 1800,  
// tuple contains four white chesses  
GGTupleTypeWWWW = 100000,  
// tuple contains at least one black and at least one white  
GGTupleTypePolluted = 0

**Comment by genosage** [comment]
随便定个值也是可以的，但会影响效果，你可以理解为这些是按照经验调整并且确定的~
